---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: ['osx-clt','osx']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew','osx']
    - role: apt
      when: ansible_os_family == "Debian"
      tags: ['apt']
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas','homebrew','osx']
    - role: kubernetes
      when: configure_kubernetes
      tags: ['kubernetes', 'containers', 'k8s']
    - role: andrewrothstein.terraform
      when: configure_terraform
      tags: ['terraform', 'iac']
  tasks:
    - include_tasks: tasks/ansible-setup.yml
