---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: true

- name: Check if /user/local/etc/ansible exists
  register: ansible_dir
  stat:
    path: /usr/local/etc/ansible

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  when: ansible_dir.stat.exists and ansible_dir.stat.isdir
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
