---
- name: Check if github.com is accessible on the destination
  register: github_online
  uri:
    url: "https://github.com"
  ignore_errors: true

- name: Include the online tasks
  when: not github_online.failed
  ansible.builtin.include_tasks: online.yml

- name: Include the offline tasks
  when: github_online.failed
  ansible.builtin.include_tasks: offline.yml
